version: '1.0.0'
services:
  yourregnumber-php:
    image: php:7.4-apache
    ports:
      - 9002:80
    volumes:
      - "./src:/var/www/html/"
  yourregnumber-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=yourregnumber_shareride_db
    ports:
      - 9003:8080
  yourregnumber-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=yourregnumber-mysql
      - PMA_PORT=3306
    ports:
      - 9004:80
    